"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";
import TechnicalReportForm from "../form";
import type { ReportData } from "../form";

type Company = { id: number; name: string; taxId: string | null };
type ReportDataWithId = ReportData & { id: number };

export default function EditTechnicalReportPage() {
  const params = useParams();
  const router = useRouter();
  const [data, setData] = useState<ReportDataWithId | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    fetch(`/api/technical-reports/${params.id}`).then(async (r) => {
      if (!r.ok) { setError("Inspección no encontrada"); return; }
      const json = await r.json();
      setData({
        id: json.id,
        companyId: String(json.companyId),
        branchId: json.branchId ? String(json.branchId) : "",
        reportType: json.reportType,
        inspectionTypes: json.inspectionTypes ? JSON.parse(json.inspectionTypes) : [json.reportType],
        title: json.title,
        status: json.status,
        qualification: json.qualification,
        contactName: json.contactName || "",
        contactPhone: json.contactPhone || "",
        contactEmail: json.contactEmail || "",
        address: json.address || "",
        city: json.city || "",
        state: json.state || "",
        gmapUrl: json.gmapUrl || "",
        connectionType: json.connectionType || "",
        bandwidth: json.bandwidth || "",
        speedDownload: json.speedDownload || "",
        speedUpload: json.speedUpload || "",
        speedLatency: json.speedLatency || "",
        speedConnectionType: json.speedConnectionType || "",
        speedIsp: json.speedIsp || "",
        speedIp: json.speedIp || "",
        powerSupply: json.powerSupply || "",
        airConditioning: json.airConditioning ?? false,
        airConditioningDetails: json.airConditioningDetails || "",
        physicalSecurity: json.physicalSecurity || "",
        cctvExistingSystem: json.cctvExistingSystem || "",
        cctvCameraCount: json.cctvCameraCount ? String(json.cctvCameraCount) : "",
        cctvCameraType: json.cctvCameraType || "",
        cctvCameraResolution: json.cctvCameraResolution || "",
        cctvCameraBrand: json.cctvCameraBrand || "",
        cctvCameraCondition: json.cctvCameraCondition || "",
        cctvDvrNvrBrand: json.cctvDvrNvrBrand || "",
        cctvDvrNvrChannels: json.cctvDvrNvrChannels || "",
        cctvStorageCapacity: json.cctvStorageCapacity || "",
        cctvRetentionDays: json.cctvRetentionDays || "",
        cctvCablingType: json.cctvCablingType || "",
        cctvCablingLength: json.cctvCablingLength ? String(json.cctvCablingLength) : "",
        cctvPowerSupply: json.cctvPowerSupply || "",
        cctvMonitoringLocation: json.cctvMonitoringLocation || "",
        cctvAreasToCover: json.cctvAreasToCover || "",
        cctvAreasCovered: json.cctvAreasCovered || "",
        cctvBlindSpots: json.cctvBlindSpots || "",
        cctvInstallationType: json.cctvInstallationType || "",
        cctvNightVision: json.cctvNightVision ?? false,
        cctvRemoteAccess: json.cctvRemoteAccess ?? false,
        cctvAlarmIntegration: json.cctvAlarmIntegration ?? false,
        cctvAccessControl: json.cctvAccessControl ?? false,
        cctvMountingLocations: json.cctvMountingLocations || "",
        cctvLightingConditions: json.cctvLightingConditions || "",
        cctvWeatherExposure: json.cctvWeatherExposure || "",
        cctvNetworkBandwidth: json.cctvNetworkBandwidth || "",
        cctvAdditionalNotes: json.cctvAdditionalNotes || "",
        netCurrentTopology: json.netCurrentTopology || "",
        netCurrentBandwidth: json.netCurrentBandwidth || "",
        netCurrentIsp: json.netCurrentIsp || "",
        netCurrentRouter: json.netCurrentRouter || "",
        netCurrentSwitch: json.netCurrentSwitch || "",
        netCurrentFirewall: json.netCurrentFirewall || "",
        netCurrentWifiAp: json.netCurrentWifiAp || "",
        netCurrentCabling: json.netCurrentCabling || "",
        netCurrentServerRoom: json.netCurrentServerRoom || "",
        netCurrentIssues: json.netCurrentIssues || "",
        netRequiredTopology: json.netRequiredTopology || "",
        netRequiredBandwidth: json.netRequiredBandwidth || "",
        netRequiredEquipment: json.netRequiredEquipment || "",
        netRequiredCabling: json.netRequiredCabling || "",
        netRequiredSecurity: json.netRequiredSecurity || "",
        netRequiredVpn: json.netRequiredVpn ?? false,
        netRequiredWifi: json.netRequiredWifi ?? false,
        netRequiredVoip: json.netRequiredVoip ?? false,
        netRequiredBackup: json.netRequiredBackup ?? false,
        netRequiredMonitoring: json.netRequiredMonitoring ?? false,
        netWifiCoverage: json.netWifiCoverage || "",
        netWifiZones: json.netWifiZones || "",
        netVlanNeeds: json.netVlanNeeds || "",
        netRemoteAccessNeeds: json.netRemoteAccessNeeds || "",
        netBackupStrategy: json.netBackupStrategy || "",
        netMaintenanceNeeds: json.netMaintenanceNeeds || "",
        netAdditionalNotes: json.netAdditionalNotes || "",
        supType: json.supType || "",
        supRemoteHours: json.supRemoteHours || "",
        supOnSiteHours: json.supOnSiteHours || "",
        supScheduleDays: json.supScheduleDays || "",
        supScheduleTimeStart: json.supScheduleTimeStart || "",
        supScheduleTimeEnd: json.supScheduleTimeEnd || "",
        supResponseTime: json.supResponseTime || "",
        supCurrentEquipBrand: json.supCurrentEquipBrand || "",
        supCurrentEquipModel: json.supCurrentEquipModel || "",
        supCurrentEquipQty: json.supCurrentEquipQty ? String(json.supCurrentEquipQty) : "",
        supCurrentEquipCondition: json.supCurrentEquipCondition || "",
        supCurrentEquipWarranty: json.supCurrentEquipWarranty || "",
        supCurrentSoftware: json.supCurrentSoftware || "",
        supCurrentIssues: json.supCurrentIssues || "",
        supRequiredServices: json.supRequiredServices || "",
        supRequiredCoverage: json.supRequiredCoverage || "",
        supRequiredSlA: json.supRequiredSlA || "",
        supRequiredTraining: json.supRequiredTraining ?? false,
        supRequiredDocumentation: json.supRequiredDocumentation ?? false,
        supRequiredInventory: json.supRequiredInventory ?? false,
        supRequiredOnSiteVisit: json.supRequiredOnSiteVisit ?? false,
        supRequiredRemoteAccess: json.supRequiredRemoteAccess ?? false,
        supClientExpectations: json.supClientExpectations || "",
        supBudgetRange: json.supBudgetRange || "",
        supContractDuration: json.supContractDuration || "",
        supAdditionalNotes: json.supAdditionalNotes || "",
        telecomNodes: json.telecomNodes ? String(json.telecomNodes) : "",
        telecomServers: json.telecomServers ? String(json.telecomServers) : "",
        telecomRacks: json.telecomRacks ? String(json.telecomRacks) : "",
        cablingType: json.cablingType || "",
        fiberDistanceM: json.fiberDistanceM ? String(json.fiberDistanceM) : "",
        networkTopology: json.networkTopology || "",
        switchRouterDetails: json.switchRouterDetails || "",
        upsRequirements: json.upsRequirements || "",
        currentSystems: json.currentSystems || "",
        erpUsers: json.erpUsers ? String(json.erpUsers) : "",
        erpModules: json.erpModules || "",
        timelineExpectations: json.timelineExpectations || "",
        dataMigration: json.dataMigration ?? false,
        trainingRequirements: json.trainingRequirements || "",
        swDevType: json.swDevType || "",
        swDevPlatform: json.swDevPlatform || "",
        swDevFeatures: json.swDevFeatures || "",
        swDevUserRoles: json.swDevUserRoles || "",
        swDevIntegrations: json.swDevIntegrations || "",
        swDevHosting: json.swDevHosting || "",
        swDevDomain: json.swDevDomain || "",
        swDevSSL: json.swDevSSL ?? false,
        swDevDatabase: json.swDevDatabase || "",
        swDevDesignReqs: json.swDevDesignReqs || "",
        swDevMobileResponsive: json.swDevMobileResponsive ?? false,
        swDevBranding: json.swDevBranding ?? false,
        swDevSecurityReqs: json.swDevSecurityReqs || "",
        swDevAuthType: json.swDevAuthType || "",
        swDevVersionControl: json.swDevVersionControl || "",
        swDevCICD: json.swDevCICD ?? false,
        swDevTesting: json.swDevTesting || "",
        swDevBudget: json.swDevBudget || "",
        swDevMaintenance: json.swDevMaintenance || "",
        swDevDocumentation: json.swDevDocumentation || "",
        swDevAdditionalNotes: json.swDevAdditionalNotes || "",
        secExistingSystem: json.secExistingSystem || "",
        secType: json.secType || "",
        secCameraCount: json.secCameraCount ? String(json.secCameraCount) : "",
        secCameraType: json.secCameraType || "",
        secCameraResolution: json.secCameraResolution || "",
        secCameraBrand: json.secCameraBrand || "",
        secCameraCondition: json.secCameraCondition || "",
        secDvrNvrType: json.secDvrNvrType || "",
        secDvrNvrBrand: json.secDvrNvrBrand || "",
        secStorageDays: json.secStorageDays ? String(json.secStorageDays) : "",
        secCablingType: json.secCablingType || "",
        secPowerSupply: json.secPowerSupply || "",
        secMonitoringLocation: json.secMonitoringLocation || "",
        secAreasToCover: json.secAreasToCover || "",
        secAreasCovered: json.secAreasCovered || "",
        secBlindSpots: json.secBlindSpots || "",
        secNightVision: json.secNightVision ?? false,
        secRemoteAccess: json.secRemoteAccess ?? false,
        secAlarmIntegration: json.secAlarmIntegration ?? false,
        secAccessControl: json.secAccessControl ?? false,
        secAdditionalNotes: json.secAdditionalNotes || "",
        cameraCount: json.cameraCount ? String(json.cameraCount) : "",
        cameraType: json.cameraType || "",
        recordingHours: json.recordingHours ? String(json.recordingHours) : "",
        storageRequirements: json.storageRequirements || "",
        monitoringNeeds: json.monitoringNeeds || "",
        nightVision: json.nightVision ?? false,
        content: json.content || "",
        findings: json.findings || "",
        recommendations: json.recommendations || "",
        justification: json.justification || "",
        observations: json.observations || "",
        blueprints: Array.isArray(json.blueprints) ? json.blueprints : [],
        photos: Array.isArray(json.photos) ? json.photos : [],
        videos: Array.isArray(json.videos) ? json.videos : [],
        documents: Array.isArray(json.documents) ? json.documents : [],
        technicianSignature: json.technicianSignature || null,
        clientSignature: json.clientSignature || null,
        clientName: json.clientName || "",
        clientDocType: json.clientDocType || "V",
        clientDocNumber: json.clientDocNumber || "",
        clientPosition: json.clientPosition || "",
        technicianSignatureLocked: json.technicianSignatureLocked ?? false,
        clientSignatureLocked: json.clientSignatureLocked ?? false,
        equipment: Array.isArray(json.equipment) ? json.equipment : typeof json.equipment === 'string' ? (() => { try { return JSON.parse(json.equipment); } catch { return []; } })() : [],
      });
    });
  }, [params.id]);

  if (error) return <div className="flex justify-center py-12 text-red-500">{error}</div>;
  if (!data) return <div className="flex justify-center py-12"><Loader2 className="h-6 w-6 animate-spin text-navy-300" /></div>;

  return <TechnicalReportForm existingData={data} />;
}
